using System.Collections.Generic;

namespace OneNoteMarkdown.Localization
{
    internal static partial class Loc
    {
        internal static readonly Dictionary<string, string> EnStrings = new Dictionary<string, string>
        {
            // ─── Ribbon labels ─────────────────────────────────────
            {"Ribbon.ImportMarkdown", "Import Markdown"},
            {"Ribbon.ExportMarkdown", "Export Markdown"},
            {"Ribbon.CopyMarkdown", "Copy Markdown"},
            {"Ribbon.RenderSelection", "Render Selection"},
            {"Ribbon.RenderPage", "Render Page"},
            {"Ribbon.RenderOutline", "Render Text Box"},
            {"Ribbon.JumpSource", "Go to Source"},
            {"Ribbon.ResetLayout", "Reset Layout"},
            {"Ribbon.DeletePreview", "Delete Preview"},
            {"Ribbon.ApplyDefaults", "Apply Defaults"},
            {"Ribbon.LiveMode", "Live Mode"},
            {"Ribbon.Settings", "Settings"},
            {"Ribbon.Help", "Help"},

            // ─── Ribbon screentips ─────────────────────────────────
            {"Ribbon.ImportMarkdown.Tip", "Import Markdown"},
            {"Ribbon.ExportMarkdown.Tip", "Export Markdown"},
            {"Ribbon.CopyMarkdown.Tip", "Copy Markdown"},
            {"Ribbon.RenderSelection.Tip", "Render Selection"},
            {"Ribbon.RenderPage.Tip", "Render Page"},
            {"Ribbon.RenderOutline.Tip", "Render Current Text Box"},
            {"Ribbon.JumpSource.Tip", "Go to linked source region"},
            {"Ribbon.ResetLayout.Tip", "Reset page preview layout"},
            {"Ribbon.DeletePreview.Tip", "Delete the current managed preview"},
            {"Ribbon.ApplyDefaults.Tip", "Apply settings to page preview"},
            {"Ribbon.LiveMode.Tip", "Live Mode"},
            {"Ribbon.Settings.Tip", "Markdown Settings"},
            {"Ribbon.Help.Tip", "Help"},

            // ─── Ribbon supertips ──────────────────────────────────
            {"Ribbon.ImportMarkdown.SuperTip", "Import Markdown source from a .md file into the current page"},
            {"Ribbon.ExportMarkdown.SuperTip", "Export the current page as a Markdown file"},
            {"Ribbon.CopyMarkdown.SuperTip", "Export the current page as Markdown and copy to clipboard"},
            {"Ribbon.RenderSelection.SuperTip", "Render the selected Markdown text into OneNote formatted content"},
            {"Ribbon.RenderPage.SuperTip", "Re-render the entire page content as Markdown"},
            {"Ribbon.RenderOutline.SuperTip", "Create an independent Markdown preview beside or below the current text box"},
            {"Ribbon.JumpSource.SuperTip", "Navigate from the current preview to its linked page, text box, or selection start"},
            {"Ribbon.ResetLayout.SuperTip", "Reposition the full-page preview using the current layout settings"},
            {"Ribbon.DeletePreview.SuperTip", "Delete the managed preview under the cursor without changing its source"},
            {"Ribbon.ApplyDefaults.SuperTip", "Explicitly reapply the current theme, default title, and layout to the full-page preview"},
            {"Ribbon.LiveMode.SuperTip", "Toggle Markdown live preview (Ctrl+\\)"},
            {"Ribbon.Settings.SuperTip", "Open theme settings to configure fonts, sizes, code line numbers, LaTeX output, etc."},
            {"Ribbon.Help.SuperTip", "View plugin features, keyboard shortcuts, and live mode instructions"},

            // ─── Dialog titles ─────────────────────────────────────
            {"Dialog.Help.Title", "OneNote Markdown - Help"},
            {"Dialog.Settings.Title", "OneNote Markdown - Settings"},
            {"Dialog.Help.Header", "✦  Help"},
            {"Dialog.Settings.Header", "✦  Theme Settings"},

            // ─── Settings dialog labels ────────────────────────────
            {"Settings.Section.Font", "Font Settings"},
            {"Settings.Section.Render", "Rendering"},
            {"Settings.Section.Preview", "Side-by-side Preview"},
            {"Settings.Section.Language", "Language"},
            {"Settings.FontFamily", "Body Font"},
            {"Settings.MonoFont", "Code Font"},
            {"Settings.MathFont", "Math Font"},
            {"Settings.ParagraphSize", "Body Font Size"},
            {"Settings.CodeSize", "Code Font Size"},
            {"Settings.EnableLatex", "Render LaTeX formulas as images"},
            {"Settings.LatexImageFormat", "LaTeX image format"},
            {"Settings.MermaidImageFormat", "Mermaid image format"},
            {"Settings.ImageFormat.Png", "PNG (default)"},
            {"Settings.ImageFormat.Emf", "EMF (vector)"},
            {"Settings.EnableLineNumber", "Show code line numbers"},
            {"Settings.AllowRemoteImages", "Allow HTTP/HTTPS images (10 MB limit)"},
            {"Settings.ImportKeepSource", "Keep editable Markdown source on the left when importing"},
            {"Settings.ThemePreset", "Style Preset"},
            {"Settings.ThemePreset.Technical", "Technical Document"},
            {"Settings.ThemePreset.Study", "Study Notes"},
            {"Settings.ThemePreset.Minimal", "Minimal"},
            {"Settings.PreviewShowTitle", "Show a title on new previews"},
            {"Settings.PreviewTitle", "Default title for new previews"},
            {"Settings.PreviewPosition", "New preview position"},
            {"Settings.PreviewPosition.Right", "Right of source"},
            {"Settings.PreviewPosition.Below", "Below source"},
            {"Settings.PreviewGap", "Preview gap"},
            {"Settings.PreviewWidth", "Preview width"},
            {"Settings.AutoRefresh", "Refresh side-by-side previews after editing"},
            {"Settings.AutoRefreshDelay", "Auto-refresh delay (milliseconds)"},
            {"Settings.Language", "UI Language"},
            {"Settings.Language.Auto", "Auto (follow system)"},
            {"Settings.Language.Zh", "中文"},
            {"Settings.Language.En", "English"},
            {"Settings.Save", "Save"},
            {"Settings.Cancel", "Cancel"},
            {"Settings.Hint", "Changes take effect after re-rendering the page (F5).\nSettings file: %AppData%\\OneNoteMarkdown\\settings\\theme.ini"},
            {"Settings.SaveFailed", "Failed to save settings: {0}"},
            {"Settings.RestartHint", "Language changes will take full effect after restarting OneNote."},

            // ─── Help tree nodes ───────────────────────────────────
            {"Help.Tree.Root", "Contents"},
            {"Help.Tree.QuickStart", "Quick Start"},
            {"Help.Tree.Features", "Features"},
            {"Help.Tree.RenderPage", "Render Page"},
            {"Help.Tree.RenderSelection", "Render Selection"},
            {"Help.Tree.LiveMode", "Live Mode"},
            {"Help.Tree.ImportExport", "Import/Export"},
            {"Help.Tree.LaTeX", "LaTeX Formulas"},
            {"Help.Tree.CodeHighlight", "Code Highlighting"},
            {"Help.Tree.Settings", "Settings"},
            {"Help.Tree.Shortcuts", "Shortcuts"},
            {"Help.Tree.FAQ", "FAQ"},
            {"Help.Tree.About", "About"},

            // ─── Messages (Features) ──────────────────────────────
            {"Msg.PageEmpty", "The current page is empty and cannot be exported."},
            {"Msg.ExportSuccess", "Page exported as Markdown successfully."},
            {"Msg.ExportFailed", "Export Markdown failed: {0}"},
            {"Msg.ExportPreviewConflict", "A managed preview body was modified. Continuing will export the saved original Markdown, not the edited preview. Continue?"},
            {"Msg.ExportUnsupportedObjects", "This page contains {0} image, attachment, media, or ink object(s) that cannot be converted reliably to Markdown. Continuing will omit them. Continue?"},
            {"Msg.PageEmptyCopy", "The current page is empty and cannot be copied."},
            {"Msg.ClipboardBusy", "Clipboard is busy, please try again later."},
            {"Msg.CopySuccess", "Page Markdown copied to clipboard."},
            {"Msg.CopyFailed", "Copy Markdown failed: {0}"},
            {"Msg.NoPage", "No page is currently open."},
            {"Msg.FileTooLarge", "File is too large (exceeds 10 MB), please select a smaller file."},
            {"Msg.FileEmpty", "The selected Markdown file is empty."},
            {"Msg.ParseEmpty", "Markdown parsing produced empty output."},
            {"Msg.ImportSuccessWithSource", "Markdown source was imported on the left with a preview on the right."},
            {"Msg.ImportSuccessPreviewOnly", "Markdown was imported as a managed preview."},
            {"Msg.ImportFailed", "Import Markdown failed: {0}"},
            {"Msg.PageContentEmpty", "The current page is empty."},
            {"Msg.RenderPageEmpty", "Full page content cannot be rendered."},
            {"Msg.RenderPageFailed", "Render page failed: {0}"},
            {"Msg.NoOutline", "Place the cursor in the text box you want to preview."},
            {"Msg.RenderOutlineFailed", "Render current text box failed: {0}"},
            {"Msg.PreviewConflict", "The preview body was edited manually. Overwrite those changes and refresh it?"},
            {"Msg.NoManagedPreview", "Place the cursor in a preview managed by the add-in."},
            {"Msg.DeletePreviewFailed", "Delete preview failed: {0}"},
            {"Msg.JumpSourceFailed", "Go to source failed: {0}"},
            {"Msg.ResetLayoutFailed", "Reset preview layout failed: {0}"},
            {"Msg.ApplyDefaultsFailed", "Apply preview settings failed: {0}"},
            {"Msg.NoSelection", "Please select some Markdown text first."},
            {"Msg.RenderSelEmpty", "Selected content cannot be rendered."},
            {"Msg.RenderSelFailed", "Render selection failed: {0}"},
            {"Msg.LiveOn", "Live mode enabled."},
            {"Msg.LiveOff", "Live mode disabled."},
            {"Msg.LiveToggleFailed", "Toggle live mode failed: {0}"},
            {"Msg.HelpFailed", "Failed to open help: {0}"},
            {"Msg.SettingsFailed", "Failed to open theme settings: {0}"},

            // ─── Common ────────────────────────────────────────────
            {"Common.AppTitle", "OneNote Markdown"},
            {"Common.Close", "Close"},
        };
    }
}
